"""
Local Search Algorithms
========================
HillClimbing           — Steepest Ascent on a 2-D grid (inherits BaseGraphSearch)
HillClimbingContinuous — Steepest Ascent for continuous functions (inherits BaseMetaheuristic)

Both use random restarts to escape local optima.
"""

import time
import numpy as np
import sys
import os

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from algorithms.base import BaseGraphSearch, BaseMetaheuristic


# ── Shared heuristic ──────────────────────────────────────────────────────────

def _manhattan(node, goal) -> float:
    return abs(node[0] - goal[0]) + abs(node[1] - goal[1])


# ══════════════════════════════════════════════════════════════════════════════
#  1. Hill Climbing — Steepest Ascent (Grid / Discrete)
# ══════════════════════════════════════════════════════════════════════════════

class HillClimbing(BaseGraphSearch):
    """
    Hill Climbing (Steepest Ascent) on a 2-D grid.

    At each step, ALL valid neighbors are evaluated; the one with the
    lowest Manhattan distance to the goal is selected (steepest descent
    on the heuristic landscape). Random restarts escape dead ends.

    Not guaranteed to find the globally shortest path — susceptible to
    local optima (dead ends / narrow corridors).

    Parameters
    ----------
    max_restarts : int
        Number of random restarts when stuck in a dead end.
    seed : int or None
        Random seed for reproducibility.
    """

    def __init__(self, grid, start_node, end_node,
                 max_restarts: int = 10, seed: int = None):
        super().__init__("HillClimbing", grid, start_node, end_node)
        self.max_restarts = max_restarts
        self.seed         = seed

    def _free_cells(self):
        """All passable (non-wall) cell coordinates."""
        return list(zip(*np.where(self.grid == 0)))

    def solve(self):
        t0 = time.time()
        if self.seed is not None:
            np.random.seed(self.seed)

        start      = self.start_node
        goal       = self.end_node
        free_cells = self._free_cells()
        best_path  = None

        for restart in range(self.max_restarts + 1):
            current = start if restart == 0 else \
                      free_cells[np.random.randint(len(free_cells))]
            path    = [current]
            visited = {current}

            while current != goal:
                neighbors = [n for n in self.get_neighbors(current)
                             if n not in visited]
                if not neighbors:
                    break                       # dead end → restart

                self.nodes_expanded += 1
                self.explored_path.append(current)

                # Steepest ascent: pick neighbor minimizing h(n, goal)
                current = min(neighbors, key=lambda n: _manhattan(n, goal))
                path.append(current)
                visited.add(current)

            if current == goal:
                if best_path is None or len(path) < len(best_path):
                    best_path = path
                break

        if best_path is not None:
            self.best_solution = best_path
            self.best_fitness  = len(best_path) - 1
        else:
            self.best_solution = []
            self.best_fitness  = float('inf')

        self.execution_time = time.time() - t0
        return self

    def get_results(self):
        results = super().get_results()
        results.update({
            "time_complexity": "O(max_restarts * n)  # n=grid size (cells)",
            "space_complexity": "O(n)  # visited set + path",
        })
        return results


# ══════════════════════════════════════════════════════════════════════════════
#  2. Hill Climbing — Steepest Ascent (Continuous)
# ══════════════════════════════════════════════════════════════════════════════

class HillClimbingContinuous(BaseMetaheuristic):
    """
    Hill Climbing (Steepest Ascent) for continuous function minimization.

    At each step, `pop_size` neighbors are generated by Gaussian perturbation;
    the best improvement is accepted (steepest descent). Step-size decay and
    random restarts help escape shallow local optima.

    Inherits BaseMetaheuristic so results plug directly into the same
    visualization pipeline as TLBO / SFO / CA.

    Parameters
    ----------
    objective_func : callable
        f(population) -> np.ndarray of shape (n,). Must be vectorised.
    pop_size : int
        Number of neighbors sampled per iteration (controls search width).
    max_iter : int
    bounds : np.ndarray, shape (dim, 2)
    dim : int
    step_size : float
        Initial Gaussian perturbation std deviation.
    step_decay : float
        Multiplicative decay applied to step_size each iteration.
    max_restarts : int
        Restart from a random point after `patience` non-improving steps.
    patience : int
        Non-improving steps before triggering a random restart.
    seed : int or None
    """

    def __init__(self, objective_func, pop_size: int = 8, max_iter: int = 500,
                 bounds: np.ndarray = None, dim: int = None,
                 step_size: float = 0.5, step_decay: float = 0.995,
                 max_restarts: int = 10, patience: int = 30,
                 seed: int = None):
        super().__init__("HillClimbingContinuous", objective_func,
                         pop_size, max_iter, bounds, dim)
        self.step_size    = step_size
        self.step_decay   = step_decay
        self.max_restarts = max_restarts
        self.patience     = patience
        self.seed         = seed

    def solve(self):
        if self.seed is not None:
            np.random.seed(self.seed)

        lb   = self.bounds[:, 0]
        ub   = self.bounds[:, 1]
        t0   = time.time()
        step = self.step_size

        # ── Initialisation ────────────────────────────────────────────────────
        current     = np.random.uniform(lb, ub, size=self.dim)
        current_fit = self.objective_func(current.reshape(1, -1))[0]

        self.best_solution = current.copy()
        self.best_fitness  = current_fit

        restarts_done = 0
        no_improve    = 0

        for t in range(self.max_iter):
            step *= self.step_decay

            # ── Steepest ascent: sample pop_size neighbors ────────────────────
            noise      = np.random.normal(0, step, size=(self.pop_size, self.dim))
            neighbors  = np.clip(current + noise, lb, ub)
            nb_fitness = self.objective_func(neighbors)

            best_idx = np.argmin(nb_fitness)
            if nb_fitness[best_idx] < current_fit:
                current     = neighbors[best_idx].copy()
                current_fit = nb_fitness[best_idx]
                no_improve  = 0
            else:
                no_improve += 1

            if current_fit < self.best_fitness:
                self.best_fitness  = current_fit
                self.best_solution = current.copy()

            # ── Random restart when stuck ──────────────────────────────────────
            if no_improve >= self.patience and restarts_done < self.max_restarts:
                current     = np.random.uniform(lb, ub, size=self.dim)
                current_fit = self.objective_func(current.reshape(1, -1))[0]
                step        = self.step_size          # reset step on restart
                no_improve  = 0
                restarts_done += 1

            # ── Track metrics ─────────────────────────────────────────────────
            self.convergence_curve[t]     = self.best_fitness
            self.average_fitness_curve[t] = current_fit
            self.diversity_curve[t]       = step       # step size proxies diversity

        self.execution_time = time.time() - t0
        return self.get_results()


# ══════════════════════════════════════════════════════════════════════════════
#  Demo
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":

    # ── Grid Hill Climbing ────────────────────────────────────────────────────
    np.random.seed(5)
    ROWS, COLS = 15, 15
    grid = np.zeros((ROWS, COLS), dtype=int)
    for r in range(ROWS):
        for c in range(COLS):
            if (r, c) not in [(0, 0), (14, 14)] and np.random.random() < 0.25:
                grid[r, c] = 1

    START, GOAL = (0, 0), (14, 14)
    hc_grid = HillClimbing(grid, START, GOAL, max_restarts=10, seed=42)
    hc_grid.solve()
    r = hc_grid.get_results()
    found = r['best_fitness'] < float('inf')
    print(f"[HillClimbing Grid]")
    print(f"  Found={found} | path={r['path_length']} | "
          f"nodes={r['nodes_expanded']} | "
          f"time={r['execution_time_seconds']*1000:.2f}ms\n")

    # ── Continuous Hill Climbing ───────────────────────────────────────────────
    def sphere(pop: np.ndarray) -> np.ndarray:
        if pop.ndim == 1:
            pop = pop.reshape(1, -1)
        return np.sum(pop ** 2, axis=1)

    DIM    = 10
    BOUNDS = np.array([[-5.12, 5.12]] * DIM)

    hc_cont = HillClimbingContinuous(
        sphere, pop_size=8, max_iter=500,
        bounds=BOUNDS, dim=DIM,
        step_size=0.5, max_restarts=10, seed=42
    )
    hc_cont.solve()
    r2 = hc_cont.get_results()
    print(f"[HillClimbingContinuous] Sphere dim={DIM}")
    print(f"  Best fitness  : {r2['best_fitness']:.6e}")
    print(f"  Execution time: {r2['execution_time_seconds']*1000:.2f}ms")

# ══════════════════════════════════════════════════════════════════════════════
#  HillClimbing_TSP — Hill Climbing for Traveling Salesman Problem (2-opt)
# ══════════════════════════════════════════════════════════════════════════════

class HillClimbing_TSP:
    """
    Hill Climbing for TSP using 2-opt local search.
    
    Starts from a random tour and iteratively applies 2-opt swaps,
    accepting improvements until reaching a local optimum.
    Multiple random restarts escape local optima.
    
    Parameters
    ----------
    dist_matrix : np.ndarray
        Symmetric distance matrix.
    max_restarts : int
        Number of random restarts after getting stuck.
    max_2opt_iterations : int
        Max 2-opt iterations per restart.
    seed : int or None
        Random seed.
    """
    
    def __init__(self, dist_matrix, max_restarts: int = 10,
                 max_2opt_iterations: int = 1000, seed: int = None):
        self.dist_matrix = np.array(dist_matrix, dtype=float)
        self.n = dist_matrix.shape[0]
        self.max_restarts = max_restarts
        self.max_2opt_iterations = max_2opt_iterations
        self.seed = seed
        
        self.best_solution = None
        self.best_fitness = float('inf')
        self.execution_time = 0.0
        self.convergence_curve = None
    
    def _tour_length(self, tour):
        """Calculate total tour distance."""
        return float(sum(
            self.dist_matrix[tour[i], tour[(i + 1) % len(tour)]]
            for i in range(len(tour))
        ))
    
    def _two_opt(self, tour, i, k):
        """Perform 2-opt swap: reverse segment [i:k+1]."""
        new_tour = tour.copy()
        new_tour[i:k + 1] = tour[i:k + 1][::-1]
        return new_tour
    
    def _local_search(self, tour):
        """Hill climbing: apply 2-opt moves until local optimum."""
        current = tour.copy()
        current_cost = self._tour_length(current)
        improved = True
        iterations = 0
        
        while improved and iterations < self.max_2opt_iterations:
            improved = False
            iterations += 1
            
            # Try all 2-opt moves
            for i in range(self.n - 1):
                for k in range(i + 2, self.n):
                    neighbor = self._two_opt(current, i, k)
                    neighbor_cost = self._tour_length(neighbor)
                    
                    if neighbor_cost < current_cost:
                        current = neighbor
                        current_cost = neighbor_cost
                        improved = True
                        break
                if improved:
                    break
        
        return current, current_cost
    
    def solve(self):
        """Run Hill Climbing with random restarts."""
        if self.seed is not None:
            np.random.seed(self.seed)
        
        t0 = time.time()
        
        for restart in range(self.max_restarts + 1):
            # Random initial tour
            tour = np.random.permutation(self.n)
            
            # Local search
            local_best, local_cost = self._local_search(tour)
            
            if local_cost < self.best_fitness:
                self.best_fitness = local_cost
                self.best_solution = local_best
        
        self.execution_time = time.time() - t0
        return self
    
    def get_results(self):
        """Return results dictionary."""
        return {
            "algorithm": "HillClimbing_TSP",
            "best_fitness": float(self.best_fitness),
            "best_solution": self.best_solution.tolist() if self.best_solution is not None else None,
            "execution_time_seconds": self.execution_time,
            "time_complexity": "O(max_restarts * max_2opt_iterations * n^2)  # 2-opt move is O(1), full check O(n^2)",
            "space_complexity": "O(n + n^2)  # current tour + distance matrix",
        }